group 'ai.pa.device'
version '0.1.1'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'ai.pa.device'
    compileSdk 36
    buildToolsVersion '36.0.0'

    defaultConfig {
        minSdk 26
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'com.google.mlkit:genai-prompt:1.0.0-beta4'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
}
